/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author ishma
 */
public class AdminSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminSearchFrame
     */
    public AdminSearchFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("Company ICON.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Namefield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        NameArea = new javax.swing.JTextArea();
        NameSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        PhoneArea = new javax.swing.JTextArea();
        PhoneSearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        GenderArea = new javax.swing.JTextArea();
        GenderBox = new javax.swing.JComboBox<>();
        GenderSearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Emailarea = new javax.swing.JTextArea();
        EmailSearch = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        AgeArea = new javax.swing.JTextArea();
        AgeSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        USERIDfield = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        USERIDarea = new javax.swing.JTextArea();
        UserIDsearch = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton4.setText("SEARCH");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search User");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 234, 234));

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 234, 234));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Enter Name : ");

        NameArea.setColumns(20);
        NameArea.setRows(5);
        jScrollPane2.setViewportView(NameArea);

        NameSearch.setBackground(new java.awt.Color(255, 204, 204));
        NameSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        NameSearch.setText("SEARCH");
        NameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Namefield, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(NameSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by Name", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 234, 234));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Enter Phone : ");

        PhoneArea.setColumns(20);
        PhoneArea.setRows(5);
        jScrollPane3.setViewportView(PhoneArea);

        PhoneSearch.setBackground(new java.awt.Color(255, 204, 204));
        PhoneSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        PhoneSearch.setText("SEARCH");
        PhoneSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(PhoneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PhoneSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by Phone", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 234, 234));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Enter Gender : ");

        GenderArea.setColumns(20);
        GenderArea.setRows(5);
        jScrollPane4.setViewportView(GenderArea);

        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female", "Third Gender", "Rather not answer" }));

        GenderSearch.setBackground(new java.awt.Color(255, 204, 204));
        GenderSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        GenderSearch.setText("SEARCH");
        GenderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(GenderSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by Gender", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 234, 234));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Enter Email : ");

        Emailarea.setColumns(20);
        Emailarea.setRows(5);
        jScrollPane1.setViewportView(Emailarea);

        EmailSearch.setBackground(new java.awt.Color(255, 204, 204));
        EmailSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        EmailSearch.setText("SEARCH");
        EmailSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by Email", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 234, 234));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Enter Age : ");

        AgeArea.setColumns(20);
        AgeArea.setRows(5);
        jScrollPane5.setViewportView(AgeArea);

        AgeSearch.setBackground(new java.awt.Color(255, 204, 204));
        AgeSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AgeSearch.setText("SEARCH");
        AgeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgeField, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgeSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by Age", jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 234, 234));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Enter UserID : ");

        USERIDarea.setColumns(20);
        USERIDarea.setRows(5);
        jScrollPane6.setViewportView(USERIDarea);

        UserIDsearch.setBackground(new java.awt.Color(255, 204, 204));
        UserIDsearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        UserIDsearch.setText("SEARCH");
        UserIDsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(USERIDfield))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(UserIDsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(USERIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserIDsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by UserID", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (Namefield.getText().contains(account.getFirstName())) {
                NameArea.append("User ID : " + account.getUserID());
                NameArea.append("\n");
                NameArea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                NameArea.append("\n");
                NameArea.append("User Email : " + account.getEmail());
                NameArea.append("\n");
                NameArea.append("User Date Of Birth : " + account.getDOB());
                NameArea.append("\n");
                NameArea.append("User Age : " + account.getAge());
                NameArea.append("\n");
                NameArea.append("User Gender : " + account.getGender());
                NameArea.append("\n");
                NameArea.append("User Phone : " + account.getPhone());
                NameArea.append("\n");
                NameArea.append("\n");
                NameArea.append("\n");
            }
        }
    }//GEN-LAST:event_NameSearchActionPerformed

    private void PhoneSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneSearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (PhoneField.getText().equals(account.getPhone())) {
                PhoneArea.append("User ID : " + account.getUserID());
                PhoneArea.append("\n");
                PhoneArea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                PhoneArea.append("\n");
                PhoneArea.append("User Email : " + account.getEmail());
                PhoneArea.append("\n");
                PhoneArea.append("User Date Of Birth : " + account.getDOB());
                PhoneArea.append("\n");
                PhoneArea.append("User Age : " + account.getAge());
                PhoneArea.append("\n");
                PhoneArea.append("\n");
                PhoneArea.append("User Gender : " + account.getGender());
                PhoneArea.append("\n");
                PhoneArea.append("User Phone : " + account.getPhone());
                PhoneArea.append("\n");
                PhoneArea.append("\n");
                PhoneArea.append("\n");
            }
        }
    }//GEN-LAST:event_PhoneSearchActionPerformed

    private void GenderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderSearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (GenderBox.getSelectedItem().equals(account.getGender())) {
                GenderArea.append("User ID : " + account.getUserID());
                GenderArea.append("\n");
                GenderArea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                GenderArea.append("\n");
                GenderArea.append("User Email : " + account.getEmail());
                GenderArea.append("\n");
                GenderArea.append("User Date Of Birth : " + account.getDOB());
                GenderArea.append("\n");
                GenderArea.append("User Age : " + account.getAge());
                GenderArea.append("\n");
                GenderArea.append("User Gender : " + account.getGender());
                GenderArea.append("\n");
                GenderArea.append("User Phone : " + account.getPhone());
                GenderArea.append("\n");
                GenderArea.append("\n");
            }
        }
    }//GEN-LAST:event_GenderSearchActionPerformed

    private void EmailSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailSearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (EmailField.getText().equals(account.getEmail())) {
                Emailarea.append("User ID : " + account.getUserID());
                Emailarea.append("\n");
                Emailarea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                Emailarea.append("\n");
                Emailarea.append("User Email : " + account.getEmail());
                Emailarea.append("\n");
                Emailarea.append("User Date Of Birth : " + account.getDOB());
                Emailarea.append("\n");
                Emailarea.append("User Age : " + account.getAge());
                Emailarea.append("\n");
                Emailarea.append("User Gender : " + account.getGender());
                Emailarea.append("\n");
                Emailarea.append("User Phone : " + account.getPhone());
                Emailarea.append("\n");
                Emailarea.append("\n");
                Emailarea.append("\n");
            }
        }
    }//GEN-LAST:event_EmailSearchActionPerformed

    private void AgeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeSearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (AgeField.getText().equals(account.getAge())) {
                AgeArea.append("User ID : " + account.getUserID());
                AgeArea.append("\n");
                AgeArea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                AgeArea.append("\n");
                AgeArea.append("User Email : " + account.getEmail());
                AgeArea.append("\n");
                AgeArea.append("User Date Of Birth : " + account.getDOB());
                AgeArea.append("\n");
                AgeArea.append("User Age : " + account.getAge());
                AgeArea.append("\n");
                AgeArea.append("User Gender : " + account.getGender());
                AgeArea.append("\n");
                AgeArea.append("User Phone : " + account.getPhone());
                AgeArea.append("\n");
                AgeArea.append("\n");
                AgeArea.append("\n");
            }
        }
    }//GEN-LAST:event_AgeSearchActionPerformed

    private void UserIDsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDsearchActionPerformed
        ArrayList<Account> accounts = new ArrayList<>();

        try (ObjectInputStream oos = new ObjectInputStream(new FileInputStream("user_database.dat"))) {
            accounts = (ArrayList<Account>) oos.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("File not found. Creating a new file.");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        for (int i = 0; i < accounts.size(); i++) {
            Account account = accounts.get(i);
            if (USERIDfield.getText().equals(account.getUserID())) {
                USERIDarea.append("User ID : " + account.getUserID());
                USERIDarea.append("\n");
                USERIDarea.append("User Name : " + account.getFirstName() + " " + account.getLastName());
                USERIDarea.append("\n");
                USERIDarea.append("User Email : " + account.getEmail());
                USERIDarea.append("\n");
                USERIDarea.append("User Date Of Birth : " + account.getDOB());
                USERIDarea.append("\n");
                USERIDarea.append("User Age : " + account.getAge());
                USERIDarea.append("\n");
                USERIDarea.append("User Gender : " + account.getGender());
                USERIDarea.append("\n");
                USERIDarea.append("User Phone : " + account.getPhone());
                USERIDarea.append("\n");
                USERIDarea.append("\n");
                USERIDarea.append("\n");
            }
        }
    }//GEN-LAST:event_UserIDsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AgeArea;
    private javax.swing.JTextField AgeField;
    private javax.swing.JButton AgeSearch;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton EmailSearch;
    private javax.swing.JTextArea Emailarea;
    private javax.swing.JTextArea GenderArea;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JButton GenderSearch;
    private javax.swing.JTextArea NameArea;
    private javax.swing.JButton NameSearch;
    private javax.swing.JTextField Namefield;
    private javax.swing.JTextArea PhoneArea;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton PhoneSearch;
    private javax.swing.JTextArea USERIDarea;
    private javax.swing.JTextField USERIDfield;
    private javax.swing.JButton UserIDsearch;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
